import './globals.css'
import { Nunito_Sans, Playfair_Display } from 'next/font/google'
import Logo from "@/app/components/Logo";
import Navbar from "@/app/components/Navbar";
import Avatar from "@/app/components/Avatar";

// font setting
const nunitoSans = Nunito_Sans({
    subsets: ['latin'],
    variable: '--font-nunitoSans',
    weight: ['200', '300', '400', '500', '600', '700', '800']
})

// font setting
const playFairDisplay = Playfair_Display({
    subsets: ['latin'],
    variable: '--font-playFairDisplay',
    weight: ['400', '500', '600', '700', '800', "900"]
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-[#F8F3ED] bg-no-repeat bg-cover ${[nunitoSans.variable, playFairDisplay.variable]} font-serif font-sans`}>
      <Logo />
      <Navbar />
      <Avatar />
      {children}
      </body>
    </html>
  )
}
