import './globals.css'
import { Nunito_Sans } from 'next/font/google'
import Logo from "@/app/components/Logo";

const nunitoSans = Nunito_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-[#F8F3ED] bg-no-repeat bg-cover ${nunitoSans.className}`}>
      <Logo />
      {children}
      </body>
    </html>
  )
}
